version: '3.8'
services:
  postgres:
    image: postgres:16.2
    container_name: my_postgres_container
    environment:
      - POSTGRES_DB=my_database
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
    ports:
      - "5432:5432"
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  my_postgres_data:
